import { NextRequest, NextResponse } from 'next/server'
import connectDB from '@/lib/mongodb'
import User from '@/models/User'

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const { privyId, username, email, walletAddress } = body

    if (!privyId) {
      return NextResponse.json(
        { error: 'Privy ID is required' },
        { status: 400 }
      )
    }

    if (!username) {
      return NextResponse.json(
        { error: 'Username is required' },
        { status: 400 }
      )
    }

    // Validate username
    if (username.length < 3 || username.length > 20) {
      return NextResponse.json(
        { error: 'Username must be between 3 and 20 characters' },
        { status: 400 }
      )
    }

    const validUsername = /^[a-zA-Z0-9_-]+$/.test(username)
    if (!validUsername) {
      return NextResponse.json(
        { error: 'Username can only contain letters, numbers, underscores, and hyphens' },
        { status: 400 }
      )
    }

    await connectDB()

    // Check if username is already taken
    const existingUsername = await User.findOne({ username, privyId: { $ne: privyId } })
    if (existingUsername) {
      return NextResponse.json(
        { error: 'Username is already taken' },
        { status: 409 }
      )
    }

    // Check if user already exists
    let user = await User.findOne({ privyId })

    if (user) {
      // Update existing user
      user.username = username
      if (email) user.email = email
      if (walletAddress) user.walletAddress = walletAddress
      await user.save()
    } else {
      // Create new user
      user = await User.create({
        privyId,
        username,
        email: email || undefined,
        walletAddress: walletAddress || undefined,
        stats: {
          wins: 0,
          losses: 0,
          totalEarned: 0,
          winRate: 0,
          currentStreak: 0,
          bestStreak: 0,
        },
      })
    }

    return NextResponse.json({
      success: true,
      user: {
        id: user._id,
        username: user.username,
        email: user.email,
      },
    })
  } catch (error: any) {
    console.error('Onboarding error:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to complete onboarding' },
      { status: 500 }
    )
  }
}

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url)
    const privyId = searchParams.get('privyId')

    if (!privyId) {
      return NextResponse.json(
        { error: 'Privy ID is required' },
        { status: 400 }
      )
    }

    await connectDB()

    const user = await User.findOne({ privyId })

    if (!user) {
      return NextResponse.json(
        { completed: false },
        { status: 200 }
      )
    }

    // Check if username was auto-generated (starts with "user_") - if so, not properly onboarded
    const isAutoGeneratedUsername = user.username.startsWith('user_')
    
    if (isAutoGeneratedUsername) {
      return NextResponse.json(
        { completed: false },
        { status: 200 }
      )
    }

    return NextResponse.json({
      completed: true,
      user: {
        id: user._id,
        username: user.username,
        email: user.email,
      },
    })
  } catch (error: any) {
    console.error('Check onboarding error:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to check onboarding status' },
      { status: 500 }
    )
  }
}

